spring:
  application:
    name: EDUREKA-SERVER

#These configurations will fetch from from config server for now we will go with application.yml only.
server:
  port: 8761
eureka:     #tells about the Eureka server details and its refresh time
  client:
    register-with-eureka: false
    fetch-registry: false
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

    
#management:
#    security:
#      enabled: false   
# 
#logging:
#    level:
#      com.java.net: DEBUG
